version: '3.1'


services:
  web:
    image: app_crud:latest
    ports:
      - 80:80
    links:
      - mysql

  mysql:
    image: mariadb:latest
    ports:
      - 12345:3306
    command: --init-file /script.sql
    volumes:
      - ./script.sql:/script.sql
    environment:
      MYSQL_DATABASE: avito_test
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
    #volumes:
      #- ./data:/var/lib/mysql
  
